example_type_data:
  - name: basic
    generator_options: ''
  - name: basic-server-rendering
    generator_options: --example-server-rendering
  - name: redux
    generator_options: --redux
  - name: redux-server-rendering
    generator_options: --redux --example-server-rendering
  # Minimum version compatibility tests - tests React 18 and Shakapacker 8.2.0
  - name: basic-minimum
    generator_options: ''
    minimum_versions: true
  - name: basic-server-rendering-minimum
    generator_options: --example-server-rendering
    minimum_versions: true
