sudo: required

language: ruby

rvm:
  # Rails 5 requires 2.2
  - 2.3.1
  - 2.4.1
  - 2.5.0
  - 2.2.6
services:
  - docker

cache:
  bundler: true
  directories:
    - node_modules # NPM packages
  yarn: true

gemfile:
  - spec/dummy/Gemfile
  - spec/dummy_no_webpacker/Gemfile.rails32

env:
  global:
    - RAILS_ENV=test
    - DRIVER=selenium_chrome
    - CHROME_BIN=/usr/bin/google-chrome
    - USE_COVERALLS=TRUE

before_install:
  - sudo apt-get update
  - sudo apt-get install -y xvfb libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen scn 1600x1200x16"

install:
  - travis_retry gem install bundler
  - travis_retry nvm install 9.11.1
  - node -v
  - travis_retry npm i -g yarn@0.27.5
  - travis_retry yarn global add babel-cli
  - travis_retry bundle install
  - travis_retry yarn
  - travis_retry yarn run build
  - bundle exec rake prepare_for_ci

before_script:
  - "export DISPLAY=:99"

script:
  - bundle exec rake

matrix:
  exclude:
    - gemfile: spec/dummy_no_webpacker/Gemfile.rails32
      rvm: 2.3.1
    - gemfile: spec/dummy_no_webpacker/Gemfile.rails32
      rvm: 2.4.1
    - gemfile: spec/dummy_no_webpacker/Gemfile.rails32
      rvm: 2.5.0
    - gemfile: spec/dummy/Gemfile
      rvm: 2.2.6

notifications:
  slack:
    secure: LfcUk4AJ4vAxWwRIyw4tFh8QNbYefMwfG/oLfsN3CdRMWMOtCOHR1GGsRhAOlfVVJ/FvHqVqWj5gK7z7CaO5Uvl7rD3/zJ8QzExKx/iH9yWj55iIPuKLzwFNnBwRpFW/cqyU2lFPPRxGD50BUn3c+qybkuSqtKZ6qtTowwqlxLa5iyM3N95aZp7MEIKCP7cPcnHfLbJyP8wBpotp/rtw62eXM2HIRJJwgjcp+n+My7VFR9DnBXNFf6R91aZHM4U4cHHDbu15HFtH8honVrzK1JQdyqMNHga+j04dFuaS7z9Q369/hsELMOBp/227+Pz7ZRfWZFK4UASguOvyeX7RmGTRpTuWLm1XJeUzfsPZVROecaSVQBve+U7F12yKqilt97QlvRXn2EGyBILqvxtFNNR4S9kgAf72/6EFgiM1TKq7i9zy6lVOnagU2+7amq7UeopX1uoFsUfNKMR7YbgV1WjF0IK95UP0b0/7ZOJlPYgi5zzkQi129qAFWSMmxGk+ZpsttHh/tjJtvAh0A3mHq/zb5w4ub/MbSyZqeDUNgGj72QArOWUFSAStQT1ybsVLeDoKPgOvVq7OV1D64rpcHjBXcqOCit8tDZ+TqkFhcYJo2cITSaqE4zJXn+4F5s7So5O8CyfKYQq+kFJCooYGmfgTUckJpGl7eIvKmL4TN9Q=
